### PR TITLE
Fix to support dot in image names

### PR DESCRIPTION
**Pull request by huapox**
One more fix, to support dot in image names. Just as #12

### CODE REVIEW

**Comment by layerssss** [comment]
@jc21 I've just hit this. Any chance to have a new DockerHub image built with this?

**Comment by jc21** [comment]
Umm good question. I'll try to get CI back tomorrow

**Comment by jc21** [comment]
It took longer than a day but it's done. New version is available at `latest`.

**Comment by layerssss** [comment]
@jc21 Great stuff! Cheers for the work, pulling now.

**Pull request merged**
